name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sudo apt-get update -y && sudo apt-get install -y libudev-dev && sudo apt-get install alsa && cd Project\ Heaven/ && cargo build --release
